#!/usr/bin/env bash
# Simple TUI: choose cloud brain + local workers, then run orchestration packet.
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
ENV_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/fable-orchestrator"
ENV_FILE="$ENV_DIR/env"
mkdir -p "$ENV_DIR"

# shellcheck disable=SC1091
[[ -f "$ENV_FILE" ]] && set -a && source "$ENV_FILE" && set +a
[[ -f "$ROOT/../../../config/defaults.env" ]] && true

prompt_choice() {
  local title="$1"; shift
  local -a items=("$@")
  echo ""
  echo "=== $title ==="
  local i=1
  for it in "${items[@]}"; do
    printf "  %d) %s\n" "$i" "$it"
    i=$((i + 1))
  done
  local n
  read -r -p "Choice [1]: " n
  n="${n:-1}"
  if [[ "$n" =~ ^[0-9]+$ ]] && (( n >= 1 && n <= ${#items[@]} )); then
    echo "${items[$((n - 1))]}"
  else
    echo "${items[0]}"
  fi
}

echo "╔══════════════════════════════════════════════════════╗"
echo "║  Fable Orchestrator — Sovereign Dual-GPU TUI         ║"
echo "║  Brain = cloud (few tokens)  │  Workers = 170HX+3090 ║"
echo "╚══════════════════════════════════════════════════════╝"

brain_raw="$(prompt_choice "Cloud brain (orchestrator only)" \
  "fable|Claude Fable 5.1 (claude CLI)" \
  "openai|GPT-5.6 Luna / OpenAI-compatible" \
  "xai|Grok (xAI)")"
FABLE_BRAIN="${brain_raw%%|*}"

heavy_raw="$(prompt_choice "Worker HEAVY (CMP 170HX 64GB, large context)" \
  "coder|LiteLLM coder (default)" \
  "architect|LiteLLM architect if configured" \
  "glm|LiteLLM glm if configured")"
FABLE_WORKER_HEAVY="${heavy_raw%%|*}"

flash_raw="$(prompt_choice "Worker FLASH (RTX 3090, loops/tests)" \
  "sidekick|LiteLLM sidekick (default)" \
  "fast|LiteLLM fast" \
  "reasoner|LiteLLM reasoner")"
FABLE_WORKER_FLASH="${flash_raw%%|*}"

export FABLE_BRAIN FABLE_WORKER_HEAVY FABLE_WORKER_FLASH
export FABLE_LITELLM_BASE="${FABLE_LITELLM_BASE:-http://127.0.0.1:4000/v1}"
export FABLE_LITELLM_KEY="${FABLE_LITELLM_KEY:-sk-local-sovereign}"
export FABLE_MAX_PARALLEL="${FABLE_MAX_PARALLEL:-2}"

# Persist non-secret choices
{
  echo "# generated by fable-tui $(date -Iseconds)"
  echo "FABLE_BRAIN=$FABLE_BRAIN"
  echo "FABLE_WORKER_HEAVY=$FABLE_WORKER_HEAVY"
  echo "FABLE_WORKER_FLASH=$FABLE_WORKER_FLASH"
  echo "FABLE_LITELLM_BASE=$FABLE_LITELLM_BASE"
  echo "FABLE_LITELLM_KEY=$FABLE_LITELLM_KEY"
  echo "FABLE_MAX_PARALLEL=$FABLE_MAX_PARALLEL"
  # preserve keys if already in env file
  if [[ -f "$ENV_FILE" ]]; then
    grep -E '^(OPENAI_API_KEY|XAI_API_KEY|FABLE_MODEL|OPENAI_BRAIN_|XAI_BRAIN_|FABLE_EFFORT)=' "$ENV_FILE" || true
  fi
} > "$ENV_FILE.tmp"
mv "$ENV_FILE.tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo ""
echo "Saved selection → $ENV_FILE"

echo ""
echo "--- Callable worker menu ---"
bash "$ROOT/worker-menu.sh"
echo ""

read -r -p "Objective (one line, or empty to abort): " objective
[[ -n "${objective//[[:space:]]/}" ]] || { echo "Aborted."; exit 0; }

MENU="$("$ROOT/worker-menu.sh")"
PACKET=$(cat <<EOF
OBJECTIVE:
$objective

ACCEPTANCE:
- Implementation complete and verified with local QC when tools exist
- Brain did not write production code

CONSTRAINTS:
- Implementation workers only: local-heavy, local-flash
- Max parallel: ${FABLE_MAX_PARALLEL}

$MENU

USER_PREFERENCES:
- Prefer dual-GPU parallelization when independent
- Token-frugal brain calls (plan then adjudicate)
EOF
)

echo ""
echo "Sending packet to brain ($FABLE_BRAIN)…"
printf '%s' "$PACKET" | bash "$ROOT/ask_fable.sh"
echo ""
echo "Next: execute the graph with OpenCode/Hermes/Codex using LiteLLM models above."
echo "QC: /opt/ai/scripts/qc-lint.sh && qc-typecheck.sh && qc-test.sh"
